# Generated by Django 2.2.14 on 2024-01-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=100)),
                ('adddress_pincode', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_index=True, max_length=100)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_email', models.CharField(db_index=True, max_length=50)),
                ('user_password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('order_status', models.CharField(default='PENDING', max_length=15)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
    ]
