# Generated by Django 4.2.9 on 2024-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_groups_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
