# Generated by Django 4.2.9 on 2024-02-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer_groups_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
