# Generated by Django 2.2.14 on 2024-01-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20240122_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='business_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gstin_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_shop_address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
