# Generated by Django 2.2.14 on 2024-01-30 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='variant_image',
            field=models.ImageField(default=12, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
    ]
