# Generated by Django 2.2.14 on 2024-01-30 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_variants_variant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='root_product',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_image',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_type',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_value', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='sellers.Product')),
                ('variants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Variants')),
            ],
        ),
    ]
