# Generated by Django 2.2.14 on 2024-01-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_auto_20240130_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='image',
            new_name='product_image',
        ),
    ]
