# Generated by Django 2.2.14 on 2024-01-30 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_auto_20240130_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='product_image',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
