# Generated by Django 2.2.14 on 2024-01-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_auto_20240130_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
