# Generated by Django 2.2.14 on 2024-01-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_auto_20240130_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='product_image',
        ),
    ]
