# Generated by Django 2.2.14 on 2024-01-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0014_attribute_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='product_image',
            new_name='variant_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
