# Generated by Django 2.2.14 on 2024-01-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0015_auto_20240130_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
