# Generated by Django 4.2.9 on 2024-02-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0016_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
