# Generated by Django 4.2.9 on 2024-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0017_seller_seller_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
