# Generated by Django 4.2.9 on 2024-02-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0018_seller_is_active_seller_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_staff',
        ),
    ]
